# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-08 13:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudentInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('percentage', models.IntegerField()),
                ('name', models.CharField(max_length=150)),
                ('backlogs', models.IntegerField()),
                ('wise', models.IntegerField(default=0)),
                ('atl', models.IntegerField(default=0)),
                ('mrnd', models.IntegerField(default=0)),
                ('iot', models.IntegerField(default=0)),
            ],
        ),
    ]
